/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import dataModel.Product;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import java.util.*;
import javax.swing.BorderFactory;
/**
 *
 * @author ThuyLM
 */
public class FrTable extends javax.swing.JFrame {

    /**
     * Creates new form FrTable
     */
    public FrTable() {
        initComponents();
        
        initModel();
        
        translate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grCat = new javax.swing.ButtonGroup();
        grLang = new javax.swing.ButtonGroup();
        pnTop = new javax.swing.JPanel();
        pnCommand = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        pnEdit = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbCat = new javax.swing.JLabel();
        txtID = new javax.swing.JFormattedTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JSpinner();
        cbCat = new javax.swing.JComboBox();
        pnBottom = new javax.swing.JPanel();
        pnData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        pnSearch = new javax.swing.JPanel();
        pnByName = new javax.swing.JPanel();
        txtSearch1 = new javax.swing.JTextField();
        pnByNameCat = new javax.swing.JPanel();
        txtSearch2 = new javax.swing.JTextField();
        rdFood = new javax.swing.JRadioButton();
        rdBeverage = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        mnMain = new javax.swing.JMenuBar();
        mnLang = new javax.swing.JMenu();
        mnEN = new javax.swing.JRadioButtonMenuItem();
        mnVN = new javax.swing.JRadioButtonMenuItem();
        mnExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        pnTop.setBackground(new java.awt.Color(204, 255, 204));
        pnTop.setLayout(new java.awt.BorderLayout());

        pnCommand.setBackground(new java.awt.Color(255, 204, 204));

        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        pnCommand.add(btnInsert);

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        pnCommand.add(btnEdit);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        pnCommand.add(btnDelete);

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrint.setText("Print");
        pnCommand.add(btnPrint);

        pnTop.add(pnCommand, java.awt.BorderLayout.SOUTH);

        pnEdit.setBackground(new java.awt.Color(204, 255, 204));
        pnEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".VnArial", 0, 18), new java.awt.Color(255, 51, 0))); // NOI18N

        lbID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbID.setText("ID");

        lbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName.setText("Name");

        lbPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPrice.setText("Price");

        lbCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCat.setText("Category");

        try {
            txtID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("P####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Food", "Beverage" }));

        javax.swing.GroupLayout pnEditLayout = new javax.swing.GroupLayout(pnEdit);
        pnEdit.setLayout(pnEditLayout);
        pnEditLayout.setHorizontalGroup(
            pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbID)
                    .addComponent(lbName))
                .addGap(34, 34, 34)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrice)
                    .addComponent(lbCat))
                .addGap(41, 41, 41)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrice)
                    .addComponent(cbCat, 0, 127, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnEditLayout.setVerticalGroup(
            pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEditLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(lbPrice)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(pnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(lbCat)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnTop.add(pnEdit, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnTop);

        pnBottom.setBackground(new java.awt.Color(255, 255, 204));
        pnBottom.setLayout(new java.awt.BorderLayout());

        pnData.setBackground(new java.awt.Color(0, 204, 204));

        tbData.setAutoCreateRowSorter(true);
        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"P001", "Coca cola", "20000", "Beverage"},
                {"P002", "7Up", "19000", "Beverage"},
                {"P003", "Pizza Italia", "120000", "Food"},
                {"P004", "Chocolate", "200000", "Food"},
                {"P005", "Cake", "170000", "Food"},
                {"P006", "Orangina", "25000", "Beverage"},
                {"P007", "Peanut", "30000", "Food"}
            },
            new String [] {
                "ID", "Name", "Price", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        javax.swing.GroupLayout pnDataLayout = new javax.swing.GroupLayout(pnData);
        pnData.setLayout(pnDataLayout);
        pnDataLayout.setHorizontalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDataLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnDataLayout.setVerticalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBottom.add(pnData, java.awt.BorderLayout.CENTER);

        pnSearch.setBackground(new java.awt.Color(255, 255, 204));
        pnSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".VnArial", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        pnByName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "By Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".VnArial", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N

        txtSearch1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnByNameLayout = new javax.swing.GroupLayout(pnByName);
        pnByName.setLayout(pnByNameLayout);
        pnByNameLayout.setHorizontalGroup(
            pnByNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnByNameLayout.createSequentialGroup()
                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );
        pnByNameLayout.setVerticalGroup(
            pnByNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnByNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnByNameCat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "By Name and Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".VnArial", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        txtSearch2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        grCat.add(rdFood);
        rdFood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdFood.setText("Food");

        grCat.add(rdBeverage);
        rdBeverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdBeverage.setText("Beverage");

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnByNameCatLayout = new javax.swing.GroupLayout(pnByNameCat);
        pnByNameCat.setLayout(pnByNameCatLayout);
        pnByNameCatLayout.setHorizontalGroup(
            pnByNameCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnByNameCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdFood)
                .addGap(33, 33, 33)
                .addComponent(rdBeverage)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(pnByNameCatLayout.createSequentialGroup()
                .addComponent(txtSearch2)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(44, 44, 44))
        );
        pnByNameCatLayout.setVerticalGroup(
            pnByNameCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnByNameCatLayout.createSequentialGroup()
                .addGroup(pnByNameCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnByNameCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdFood)
                    .addComponent(rdBeverage))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnSearchLayout = new javax.swing.GroupLayout(pnSearch);
        pnSearch.setLayout(pnSearchLayout);
        pnSearchLayout.setHorizontalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnByNameCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnSearchLayout.setVerticalGroup(
            pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnByNameCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnByName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnBottom.add(pnSearch, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnBottom);

        mnLang.setText("Language");

        grLang.add(mnEN);
        mnEN.setSelected(true);
        mnEN.setText("English");
        mnEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnENActionPerformed(evt);
            }
        });
        mnLang.add(mnEN);

        grLang.add(mnVN);
        mnVN.setText("Vietnamese");
        mnVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVNActionPerformed(evt);
            }
        });
        mnLang.add(mnVN);

        mnMain.add(mnLang);

        mnExit.setText("Exit");
        mnMain.add(mnExit);

        setJMenuBar(mnMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // gia su nhu cac du lieu da duoc kiem tra ok
        // tao ra 1 doi tuong Product tu cac so lieu nay
        String id = txtID.getText().trim();
        String name = txtName.getText().trim();
        String cat = cbCat.getSelectedItem().toString();
        int price = Integer.parseInt(txtPrice.getValue().toString());
        
        Product p = new Product(id, name, cat, price);
        
        //dua sp moi nay vo model, de hien thi len jTable
        model.addRow(p.toVector());
        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
        //thiet lap chuoi chua dk loc du lieu
        String dk = txtSearch1.getText().trim();
        //tao doi tuong loc du lieu tren model
        RowFilter filter = RowFilter.regexFilter("(?i)"+dk, 1);
        sorter.setRowFilter(filter);
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void mnENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnENActionPerformed
        // TODO add your handling code here:
        translate();
    }//GEN-LAST:event_mnENActionPerformed

    private void mnVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVNActionPerformed
        // TODO add your handling code here:
        translate();
    }//GEN-LAST:event_mnVNActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String dk1 = txtSearch2.getText().trim();
        String dk2 = rdFood.isSelected()?"Food":"Beverage";
        
        //ArrayList<Rowilter<TableModel,Object>> dk = new ArrayList<>();
        ArrayList dk = new ArrayList();
        dk.add(RowFilter.regexFilter("(?)"+dk1, 1));
        dk.add(RowFilter.regexFilter(dk2, 3));
        
        sorter.setRowFilter(RowFilter.andFilter(dk));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        //lay chi so dong dang duoc chon
        
        int r = tbData.getSelectedRow();
        if(r<0) return;
        
        //lay du lieu cua cac cot tren dong duoc chon
        //cot thu 1
        String id = tbData.getValueAt(r, 0).toString();
        txtID.setText(id);
        
        //tuong tu cho cac con lai
        txtName.setText(tbData.getValueAt(r, 1).toString());
        
        int p = Integer.parseInt(tbData.getValueAt(r, 2).toString());
                
        txtPrice.setValue(p);
        cbCat.setSelectedItem(tbData.getValueAt(r, 3));
        
    }//GEN-LAST:event_tbDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cbCat;
    private javax.swing.ButtonGroup grCat;
    private javax.swing.ButtonGroup grLang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCat;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JRadioButtonMenuItem mnEN;
    private javax.swing.JMenu mnExit;
    private javax.swing.JMenu mnLang;
    private javax.swing.JMenuBar mnMain;
    private javax.swing.JRadioButtonMenuItem mnVN;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnByName;
    private javax.swing.JPanel pnByNameCat;
    private javax.swing.JPanel pnCommand;
    private javax.swing.JPanel pnData;
    private javax.swing.JPanel pnEdit;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JPanel pnTop;
    private javax.swing.JRadioButton rdBeverage;
    private javax.swing.JRadioButton rdFood;
    private javax.swing.JTable tbData;
    private javax.swing.JFormattedTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JSpinner txtPrice;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSearch2;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel model;
    TableRowSorter<TableModel> sorter;
    
    private void initModel() {
        //khoi tao mo hinh du lieu cho jTable tbData
        model = (DefaultTableModel) tbData.getModel();
        
        //vi du, dua vo 2 san pham
        Product p = new Product("P1000", "Coca coca", "Beverage", 13000);
        model.addRow(p.toVector());
        model.addRow(new Product("P1001","7 up","Beverage",13000).toVector());
        
        //khoi tao bo sap xep de loc du lieu cho chuc nang search
        sorter = (TableRowSorter<TableModel>) tbData.getRowSorter();
    }

    Locale loc;
    ResourceBundle rb;
    private void translate() {
        //khoi tao doi tuong Locale theo ngon ngu muon trinh bay
        if(mnEN.isSelected()){
            loc = new Locale("en", "US");
        }
        else{
            loc = new Locale("vi", "VN");
        }
        
        //khoi tao doi tuong ResourBundle de doc du lieu
        //tu cac tu dien co ngon ngu tuong ung duoc chon
        //thong qua bien locale
        rb = ResourceBundle.getBundle("dic.td",loc);
        
        //doc du lieu trong tu dien gan cho cac caption tuong ung
        this.setTitle(rb.getString("frTitle"));
        mnLang.setText(rb.getString("mnLang"));
        mnExit.setText(rb.getString("mnExit"));
        mnEN.setText(rb.getString("mnEN"));
        mnVN.setText(rb.getString("mnVN"));
        
        pnEdit.setBorder(BorderFactory.createTitledBorder(rb.getString("pnEdit")));
        lbID.setText(rb.getString("lbID"));
        lbName.setText(rb.getString("lbName"));
        
        String[]header = rb.getString("tbData").split(",");
        model.setColumnIdentifiers(header);       
    }
}
